#!/usr/bin/env bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

REPO_URL="https://github.com/kovalromank/arch.git"
MIRRORLIST_URL="https://archlinux.org/mirrorlist/?country=CA&protocol=https&use_mirror_status=on"

pacman -Sy --noconfirm pacman-contrib dialog git

echo "Updating mirror list"
curl -s "$MIRRORLIST_URL" | \
    sed -e 's/^#Server/Server/' -e '/^#/d' | \
    rankmirrors -n 5 - > /etc/pacman.d/mirrorlist

### Get infomation from user ###
hostname=$(dialog --stdout --inputbox "Enter hostname" 0 0) || exit 1
clear
: ${hostname:?"hostname cannot be empty"}

user=$(dialog --stdout --inputbox "Enter admin username" 0 0) || exit 1
clear
: ${user:?"user cannot be empty"}

password=$(dialog --stdout --passwordbox "Enter admin password" 0 0) || exit 1
clear
: ${password:?"password cannot be empty"}
password2=$(dialog --stdout --passwordbox "Enter admin password again" 0 0) || exit 1
clear
[[ "$password" == "$password2" ]] || ( echo "Passwords did not match"; exit 1; )

devicelist=$(lsblk -plnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
device_boot=$(dialog --stdout --menu "Select boot partition" 0 0 0 ${devicelist}) || exit 1
device=$(dialog --stdout --menu "Select root partition" 0 0 0 ${devicelist}) || exit 1
clear

### Set up logging ###
exec 1> >(tee "stdout.log")
exec 2> >(tee "stderr.log")

timedatectl set-ntp true

### Setup the disk and partitions ###
part_boot=$device_boot
part_root=$device

wipefs "${part_root}"

mkfs.ext4 -f "${part_root}"

mount "${part_root}" /mnt
mkdir -p /mnt/boot/efi
mount "${part_boot}" /mnt/boot/efi

### Install and configure the basic system ###
pacstrap /mnt base

mkdir -p /mnt/root/kovalromank-arch
git clone "${REPO_URL}" /mnt/root/kovalromank-arch

arch-chroot /mnt cd /root/kovalromank-arch/pkg/base && makepkg -si --noconfirm

genfstab -t PARTUUID /mnt >> /mnt/etc/fstab
echo "${hostname}" > /mnt/etc/hostname

cat >> /mnt/etc/hosts <<EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   $hostname.localdomain   $hostname
EOF

ln -sf /mnt/usr/share/zoneinfo/America/Toronto /mnt/etc/localtime
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
sed 's/#en_US/en_US/' -i /mnt/etc/locale.gen
arch-chroot /mnt locale-gen

arch-chroot /mnt useradd -mU -s /usr/bin/zsh -G wheel,sudo "$user"
arch-chroot /mnt chsh -s /usr/bin/zsh

echo "$user:$password" | chpasswd --root /mnt
echo "root:$password" | chpasswd --root /mnt

git clone "${REPO_URL}" "/mnt/home/${user}/kovalromank-arch"

